import { ChatMessage, AppSettings, WorldData } from "../../../types";
import { getAiClient } from "../client";
import { vectorService } from "../vectorService";
import { storyBibleService } from "../storyBibleService";

export const DynamicMemoryService = {
  /**
   * Run background summarization: Nạp "Ký ức cốt lõi" vào VectorDB và tóm tắt cốt truyện.
   */
  async processCoreMemories(
    recentHistory: ChatMessage[],
    worldData: WorldData,
    settings: AppSettings,
    campaignId: string
  ): Promise<string | null> {
    if (!settings.enableVectorMemory) return null;
    
    // We only summarize if we have enough recent history (e.g., 10 turns = 20 messages)
    if (recentHistory.length < 10) return null;

    console.log("[DynamicMemoryService] Starts summarizing core memories in background...");

    try {
      const aiClient = getAiClient(settings);
      
      const historyText = recentHistory
        .map(m => `[${m.role === 'user' ? 'Người chơi' : 'Hệ thống'}]: ${m.text.replace(/<think(?:ing)?>[\s\S]*?<\/think(?:ing)?>/gi, "").trim()}`)
        .join("\n\n");

      // Prompt for Core Memory summarization
      const prompt = `Phân tích lịch sử diễn biến trong các lượt vừa qua cùng tóm tắt cốt truyện cũ (nếu có).
Hãy tóm tắt ngắn gọn các "Ký ức cốt lõi" (Core Memories), bao gồm:
1. Tiến trình cốt truyện chính đã xảy ra.
2. Thay đổi trạng thái/quan hệ nhân vật.
3. Các sự kiện/quyết định mang tính bước ngoặt.

Viết dưới dạng đoạn văn vắn tắt, cô đọng nhất có thể (tối đa 300 từ).

Tóm tắt cũ (nếu có):
${worldData.summary || "Chưa có"}

Lịch sử giao tiếp gần đây:
${historyText}

Chỉ trả về phần chữ tóm tắt, không thêm lời bình hay mô tả dư thừa.`;

      const response = await aiClient.models.generateContent({
        model: settings.aiMode === 'hybrid' && settings.backgroundAiModel ? settings.backgroundAiModel : (settings.aiModel || "gemini-3.1-pro-preview"),
        contents: [{ role: "user", parts: [{ text: prompt }] }],
        config: {
          temperature: 0.3,
          maxOutputTokens: 600,
        },
      });

      let coreMemoryText = response.text?.trim() || "";
      if (!coreMemoryText) return null;

      // Xóa markdown, thẻ kỹ thuật nếu có
      coreMemoryText = coreMemoryText.replace(/```(json|txt)?\n?|```/g, "").trim();

      console.log("[DynamicMemoryService] Core Memory Generated: ", coreMemoryText);

      // Save into VectorDB as Core Memory (StoryBible Fact)
      await storyBibleService.saveEntry({
        id: `core-mem-${Date.now()}`,
        title: `Ký ức cốt lõi (Lượt ${Math.floor(recentHistory.length / 2)})`,
        category: "event",
        content: coreMemoryText,
        keywords: ["trí nhớ", "core memory", "tóm tắt", "sự kiện chính"],
        tags: ["core_memory"],
        triggerMode: "semantic",
        priority: 100, // Very important
        weight: 1.5,
        sticky: false,
        stickyTurns: 0,
        position: "before_history",
        depth: 0,
        timesTriggered: 0,
        confidence: 1.0,
        source: "auto",
        version: 1,
        createdAt: Date.now(),
        updatedAt: Date.now(),
        changelog: ["Generated by DynamicMemoryService"]
      }, campaignId, settings, true);

      // Save to vector directly as well so RAG catches it immediately
      await vectorService.saveVector(
        `core-vector-${Date.now()}`,
        coreMemoryText,
        "model",
        settings
      );

      // Return the new summary
      return coreMemoryText;

    } catch (e) {
      console.error("[DynamicMemoryService] Core memory summarization failed:", e);
      return null;
    }
  },

  /**
   * Evaluate Persona Drift using StoryBible and recent history
   */
  async checkPersonaDrift(
    recentHistory: ChatMessage[],
    worldData: WorldData,
    settings: AppSettings,
    campaignId: string
  ): Promise<{ hasDrift: boolean; reason: string } | null> {
    if (!settings.enableVectorMemory) return null;
    if (recentHistory.length < 5) return null; // Need some context

    console.log("[DynamicMemoryService] Starts Persona Drift Check...");

    try {
      const aiClient = getAiClient(settings);
      
      const historyText = recentHistory
        .map(m => `[${m.role === 'user' ? 'Người chơi' : 'Hệ thống'}]: ${m.text.replace(/<think(?:ing)?>[\s\S]*?<\/think(?:ing)?>/gi, "").trim()}`)
        .join("\n\n");

      // Extract Persona context
      const entitiesContext = worldData.entities.slice(0, 3).map(e => `Nhân vật: ${e.name}\nTính cách/Đặc điểm: ${e.personality || e.description}`).join("\n\n");

      const prompt = `Bạn là Persona Consistency Checker.
Hãy so sánh những hành động/lời thoại của các nhân vật chính trong lịch sử gần đây với hồ sơ tính cách (Persona) gốc rễ của họ.
Hồ sơ tính cách gốc:
${entitiesContext}

Lịch sử giao tiếp gần đây:
${historyText}

Nhiệm vụ: Phân tích xem có dấu hiệu "OOC" (Out Of Character - Đi lạc khỏi tính cách gốc) ở phần người kể chuyện/Hệ thống ảo không. Đặc biệt chú ý nhân vật chính.
Nếu CÓ: Trả về JSON { "hasDrift": true, "reason": "(giải thích ngắn gọn 1-2 câu về sự sai lệch)" }
Nếu KHÔNG: Trả về JSON { "hasDrift": false, "reason": "" }
Chỉ trả về JSON hợp lệ.`;

      const response = await aiClient.models.generateContent({
        model: settings.aiMode === 'hybrid' && settings.backgroundAiModel ? settings.backgroundAiModel : "gemini-2.5-flash",
        contents: [{ role: "user", parts: [{ text: prompt }] }],
        config: {
          temperature: 0.1,
          responseMimeType: "application/json"
        },
      });

      const text = response.text?.trim() || "";
      if (!text) return null;
      const parsed = JSON.parse(text);
      
      if (parsed.hasDrift) {
         // Log to StoryBible as an anomaly to self-correct
         await storyBibleService.saveEntry({
            id: `drift-${Date.now()}`,
            title: `Cảnh báo OOC (Lượt ${Math.floor(recentHistory.length / 2)})`,
            category: "concept",
            content: `Hệ thống phát hiện dấu hiệu Out Of Character: ${parsed.reason}. HÃY TỰ ĐIỀU CHỈNH LẠI HÀNH VI VÀ LỜI NÓI CHO ĐÚNG VỚI TÍNH CÁCH GỐC.`,
            keywords: ["ooc", "cảnh báo", "nhân vật", "drift"],
            tags: ["system_alert"],
            triggerMode: "always",
            priority: 200, 
            weight: 2.0,
            sticky: true,
            stickyTurns: 3, 
            position: "system_top",
            depth: 0,
            timesTriggered: 0,
            confidence: 1.0,
            source: "auto",
            version: 1,
            createdAt: Date.now(),
            updatedAt: Date.now(),
            changelog: ["Generated by Persona Drift Checker"]
          }, campaignId, settings, true);
      }

      return parsed;
    } catch (e) {
      console.error("[DynamicMemoryService] Persona drift check failed:", e);
      return null;
    }
  }
};
